stages:
  - test

test:
  stage: test
  tags:
    - tagspr  # Используем ваш тег вместо docker
  before_script:
    - choco install maven -y --no-progress  # Устанавливаем Maven через Chocolatey
    - choco install jdk17 -y --no-progress  # Устанавливаем JDK 17
    - refreshenv  # Обновляем переменные среды
    - mvn --version  # Проверяем установку Maven
    - java --version  # Проверяем установку Java
  script:
    - mvn clean test
    - echo "Tests completed"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - target/allure-results/
    reports:
      junit: target/surefire-reports/*.xml