stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  tags:
    - tagspr
  before_script:
    - choco install jdk17 -y --no-progress
    - choco install maven -y --no-progress
    - refreshenv
    - mvn --version
    - java --version
  script:
    - mvn clean test
  after_script:
    - echo "Tests completed"
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - target/allure-results/
    reports:
      junit: target/surefire-reports/*.xml