stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

run-tests:
  stage: test
  image: maven:3.8.6-openjdk-17  # Образ с Maven и Java
  services:
    - selenium/standalone-chrome:latest  # Готовый контейнер с Chrome
  script:
    - mvn clean test -Dselenium.browser=chrome -Dwebdriver.base.url=${WEB_TEST_URL}
  artifacts:
    paths:
      - target/surefire-reports/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"